requirements change 287

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -58,7 +58,13 @@ jobs:
       # Step 7: Clean and Replace site contents
       - name: Clean and Replace site contents
         run: |
-          # Remove all files except for the .git directory
+          # Ensure the .git directory exists
+          if [ ! -d ".git" ]; then
+            echo ".git directory is missing!"
+            exit 1
+          fi
+
+          # Remove all files except for the .git directory and .gitignore
           find . -mindepth 1 ! -name '.git' ! -name '.gitignore' -exec rm -rf {} +
 
           # Check if the 'site' directory has files and copy them
